config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save!
      redirect_to list_path(@list)
    else
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save!
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Bookmarks#new</h1>
<p>Find me in app/views/bookmarks/new.html.erb</p>
<h1>Add a movie to <%= @list.name %></h1>
<%= form_with model: [@list, @bookmark], local: true do |form| %>
    <div class=“form-group”>
        <%= form.label :movie_id %>
        <%= form.collection_select :movie_id, Movie.all, :id, :title, prompt: true, class: 'form-control' %>
    </div>
    <div class=“form-group”>
        <%= form.label :comment %>
        <%= form.text_area :comment, class: ‘form-control’ %>
    </div>
    <%= form.submit ‘Add’, class: ‘btn btn-primary’ %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<% @lists.each do |list| %>
  <%= link_to list.name, list_path(list) %>
<% end %>

<%= link_to "Créer une nouvelle liste", new_list_path %>

app/views/lists/new.html.erb
 <div class= "container" >
 <%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/lists/show.html.erb
<%= @list.name %>

<% @list.bookmarks.each do |bookmark|%>
  <%= bookmark.movie.title %>
  <%= bookmark.comment %>
  <%= link_to "Supprimer ce commentaire", bookmark_path(bookmark), data: {turbo_method: :delete} %>
<% end %>

<!-- lists/:id/bookmarks -->
<!-- /bookmarks -->
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.input :movie_id, collection: Movie.all %>
  <%= f.button :submit %>
<% end %>

<div>
<img src=" https://i.pinimg.com/564x/ef/70/38/ef7038b96cc8f0b3a4b815a35196765a.jpg ">
</div>


<%= link_to "Toutes les listes", lists_path %>